# Profile para SQL Server instalado na maquina local.
spring.datasource.url=${LOCAL_DB_URL:jdbc:sqlserver://localhost:1433;databaseName=ZeroUm3a;encrypt=false;trustServerCertificate=true;loginTimeout=30}
spring.datasource.username=${LOCAL_DB_USERNAME:sa}
spring.datasource.password=${LOCAL_DB_PASSWORD:@ITB123456}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
