spring.application.name=Zeroum
server.port=8080

# Conexão SQL Server (Somee)
spring.datasource.url=jdbc:sqlserver://ZeroUm3a.mssql.somee.com:1433;databaseName=ZeroUm3a;encrypt=true;trustServerCertificate=true;loginTimeout=30
spring.datasource.username=ZeroUm
spring.datasource.password=@ITB123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl